#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MineFine.Resource", IsApplication=true)]

namespace MineFine
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Adamantite_Ore = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int buttton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Coal_Ore = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Copper_Ore = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Depleted_Ore = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int exam = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int frog = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int genie = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Gold_Ore = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Iron_Ore = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int levelupp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int mainscreen = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Mithril_Ore = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int quiz = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int RuneScape_Lumgenstor = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Runite_Ore = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Silver_Ore = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Tin_Ore = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int Level = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int Upgrade = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int amountOfOre = 2131034128;
			
			// aapt resource value: 0x7f050002
			public const int btnLeft = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int btnRight = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int gp = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int levelupText = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout1 = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int listViewOreImage = 2131034126;
			
			// aapt resource value: 0x7f050006
			public const int mainImage = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int midText = 2131034113;
			
			// aapt resource value: 0x7f05000f
			public const int oreName = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int shopMenu = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int toMain = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int toShop = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int topText = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int totalExp = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomDialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int levelUp = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Shop = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ShopListViewLayout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int ApplicationName = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int Upgrade = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int expHour = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int toMain = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int toShop = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int totalExp = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
